[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# This combines both remappings and uses a more specific path for Chainlink.
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@chainlink/contracts/src/v0.8/=lib/chainlink-brownie-contracts/contracts/src/v0.8/shared/'
]
